modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
[[mods]]
modId="borealis"
version="${file.jarVersion}"
displayName="Borealis"
logoFile="logo.png"
logoBlur=false
credits="Thanks to Quek04 for framework code, Screem for a few textures, and ShrekRightTesticle for ideas"
authors="reetam"
description='''Welcome to Borealis, the winter wonderland of the sky.'''

[[dependencies.borealis]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.borealis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.5]"
    ordering="NONE"
    side="BOTH"