modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
[[mods]]
modId="borealis"
version="${file.jarVersion}"
displayName="Borealis"
logoFile="logo.png"
logoBlur=false
credits="QUEK HAS HELPED ME SOOOOOO MCUH I'D BE DEAD WITHOUT HIM, THANKS SCREEM ALSO FOR TEXTURES I CANT TEXTURE SO THANKS"
authors="reetam"
description='''Welcome to Borealis, the winter wonderland of the sky.'''
[[dependencies.borealis]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.borealis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.4]"
    ordering="NONE"
    side="BOTH"