modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="borealis"
version="${file.jarVersion}"
displayName="Borealis"
logoFile="logo.png"
logoBlur=false
credits="Thanks to Quek04 for framework code, Screem for a few textures, and ShrekRightTesticle for ideas"
authors="reetam"
description='''Welcome to Borealis, the winter wonderland of the sky.'''

[[dependencies.borealis]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.borealis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"