modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="borealis"
version="${file.jarVersion}"
displayName="Borealis"
logoFile="logo.png"
logoBlur=false
credits=""
authors="reetling"
description='''Welcome to Borealis, the winter wonderland of the sky.'''

[[dependencies.borealis]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.19,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.borealis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"