modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory

license="MIT"

[[mods]] #mandatory
modId="borealis" #mandatory
version="0.1.0" #mandatory
displayName="Borealis" #mandatory
authors="reetamb" #optional
description='''
Be the first to discover and leave your mark on this new world.
'''
enumExtensions = "META-INF/enumextensions.json"

[[mixins]]
config="borealis.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.borealis]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[21.0.0-beta,)" #mandatory
ordering="NONE"
side="BOTH"

# Here's another dependency
[[dependencies.borealis]]
modId="minecraft"
type="required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.21,1.21.1)"
ordering="NONE"
side="BOTH"